### ISSUE TITLE
NameError: name 'buffer' is not defined

### ISSUE THREAD

**Issue by avijitnsec** [arachnidlabs/mcp2210#16]
Got the following issue when working with Python 3.7 on Windows 10.
Traceback (most recent call last):
  File "C:/Users/avijit.das/PycharmProjects/SampleTest/sample1.py", line 6, in <module>
    dev = MCP2210(vid, pid)
  File "C:\Users\avijit.das\PycharmProjects\sample\venv\lib\site-packages\mcp2210\device.py", line 123, in __init__
    self.cancel_transfer()
  File "C:\Users\avijit.das\PycharmProjects\sample\venv\lib\site-packages\mcp2210\device.py", line 224, in cancel_transfer
    self.sendCommand(commands.CancelTransferCommand())
  File "C:\Users\avijit.das\PycharmProjects\sample\venv\lib\site-packages\mcp2210\device.py", line 134, in sendCommand
    command_data = [ord(x) for x in buffer(command)]
NameError: name 'buffer' is not defined

Process finished with exit code 1

**Comment by avijitnsec** [comment]
Source Code:
from mcp2210 import MCP2210
vid=0x04d8
pid=0x00de
dev = MCP2210(vid, pid)
dev.transfer("data")

dev.manufacturer_name = "Foobar Industries Ltd"
settings = dev.boot_chip_settings

print(settings)

**Comment by tracernz** [comment]
mcp2210 only supports Python 2. See http://python3porting.com/differences.html#buffer for the fix for this particular issue.
